export interface User {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  age: number;
  startDate: Date;
  endDate: Date;
}

export const usersData: User[] = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    age: 28,
    startDate: new Date("2020-01-01"),
    endDate: new Date("2023-01-01"),
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    age: 34,
    startDate: new Date("2018-05-15"),
    endDate: new Date("2022-12-30"),
  },
  {
    id: 3,
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    age: 25,
    startDate: new Date("2021-09-23"),
    endDate: new Date("2024-09-23"),
  },
  {
    id: 4,
    firstName: "Bob",
    lastName: "Brown",
    email: "bob.brown@example.com",
    age: 40,
    startDate: new Date("2015-06-10"),
    endDate: new Date("2023-11-20"),
  },
  {
    id: 5,
    firstName: "Charlie",
    lastName: "Davis",
    email: "charlie.davis@example.com",
    age: 30,
    startDate: new Date("2019-03-11"),
    endDate: new Date("2024-06-05"),
  },
  {
    id: 6,
    firstName: "David",
    lastName: "Martinez",
    email: "david.martinez@example.com",
    age: 37,
    startDate: new Date("2017-01-25"),
    endDate: new Date("2021-10-11"),
  },
  {
    id: 7,
    firstName: "Eva",
    lastName: "Lopez",
    email: "eva.lopez@example.com",
    age: 22,
    startDate: new Date("2020-07-14"),
    endDate: new Date("2025-03-18"),
  },
  {
    id: 8,
    firstName: "Frank",
    lastName: "Gonzalez",
    email: "frank.gonzalez@example.com",
    age: 45,
    startDate: new Date("2014-08-01"),
    endDate: new Date("2023-05-16"),
  },
  {
    id: 9,
    firstName: "Grace",
    lastName: "Harris",
    email: "grace.harris@example.com",
    age: 31,
    startDate: new Date("2016-02-20"),
    endDate: new Date("2021-08-30"),
  },
  {
    id: 10,
    firstName: "Henry",
    lastName: "Clark",
    email: "henry.clark@example.com",
    age: 29,
    startDate: new Date("2018-09-10"),
    endDate: new Date("2022-12-25"),
  },
  {
    id: 11,
    firstName: "Ivy",
    lastName: "Allen",
    email: "ivy.allen@example.com",
    age: 26,
    startDate: new Date("2021-05-06"),
    endDate: new Date("2024-01-15"),
  },
  {
    id: 12,
    firstName: "Jack",
    lastName: "Young",
    email: "jack.young@example.com",
    age: 35,
    startDate: new Date("2016-10-22"),
    endDate: new Date("2020-12-30"),
  },
  {
    id: 13,
    firstName: "Kathy",
    lastName: "King",
    email: "kathy.king@example.com",
    age: 41,
    startDate: new Date("2013-11-18"),
    endDate: new Date("2024-08-08"),
  },
  {
    id: 14,
    firstName: "Leo",
    lastName: "Wright",
    email: "leo.wright@example.com",
    age: 33,
    startDate: new Date("2015-12-03"),
    endDate: new Date("2023-02-18"),
  },
  {
    id: 15,
    firstName: "Mia",
    lastName: "Scott",
    email: "mia.scott@example.com",
    age: 27,
    startDate: new Date("2019-04-17"),
    endDate: new Date("2022-11-22"),
  },
  {
    id: 16,
    firstName: "Nick",
    lastName: "Adams",
    email: "nick.adams@example.com",
    age: 38,
    startDate: new Date("2014-05-05"),
    endDate: new Date("2023-10-10"),
  },
  {
    id: 17,
    firstName: "Olivia",
    lastName: "Baker",
    email: "olivia.baker@example.com",
    age: 32,
    startDate: new Date("2017-07-09"),
    endDate: new Date("2024-02-27"),
  },
  {
    id: 18,
    firstName: "Paul",
    lastName: "Carter",
    email: "paul.carter@example.com",
    age: 44,
    startDate: new Date("2012-09-14"),
    endDate: new Date("2023-01-19"),
  },
  {
    id: 19,
    firstName: "Quincy",
    lastName: "Evans",
    email: "quincy.evans@example.com",
    age: 39,
    startDate: new Date("2016-01-29"),
    endDate: new Date("2022-03-04"),
  },
  {
    id: 20,
    firstName: "Rachel",
    lastName: "Green",
    email: "rachel.green@example.com",
    age: 29,
    startDate: new Date("2018-06-11"),
    endDate: new Date("2022-12-17"),
  },
  {
    id: 21,
    firstName: "Sam",
    lastName: "Martinez",
    email: "sam.martinez@example.com",
    age: 25,
    startDate: new Date("2021-04-20"),
    endDate: new Date("2025-09-03"),
  },
  {
    id: 22,
    firstName: "Tina",
    lastName: "Roberts",
    email: "tina.roberts@example.com",
    age: 30,
    startDate: new Date("2018-02-02"),
    endDate: new Date("2023-08-15"),
  },
  {
    id: 23,
    firstName: "Ursula",
    lastName: "Hughes",
    email: "ursula.hughes@example.com",
    age: 36,
    startDate: new Date("2017-10-12"),
    endDate: new Date("2022-12-01"),
  },
  {
    id: 24,
    firstName: "Victor",
    lastName: "King",
    email: "victor.king@example.com",
    age: 42,
    startDate: new Date("2015-01-28"),
    endDate: new Date("2023-11-25"),
  },
  {
    id: 25,
    firstName: "Wendy",
    lastName: "Lopez",
    email: "wendy.lopez@example.com",
    age: 33,
    startDate: new Date("2016-06-17"),
    endDate: new Date("2021-09-09"),
  },
  {
    id: 26,
    firstName: "Xander",
    lastName: "Morris",
    email: "xander.morris@example.com",
    age: 28,
    startDate: new Date("2019-10-05"),
    endDate: new Date("2024-07-18"),
  },
  {
    id: 27,
    firstName: "Yara",
    lastName: "Nelson",
    email: "yara.nelson@example.com",
    age: 31,
    startDate: new Date("2017-02-11"),
    endDate: new Date("2022-05-23"),
  },
  {
    id: 28,
    firstName: "Zachary",
    lastName: "Perez",
    email: "zachary.perez@example.com",
    age: 38,
    startDate: new Date("2014-09-07"),
    endDate: new Date("2023-07-30"),
  },
  {
    id: 29,
    firstName: "Aaron",
    lastName: "Roberts",
    email: "aaron.roberts@example.com",
    age: 28,
    startDate: new Date("2020-01-30"),
    endDate: new Date("2023-12-12"),
  },
  {
    id: 30,
    firstName: "Beth",
    lastName: "Walker",
    email: "beth.walker@example.com",
    age: 30,
    startDate: new Date("2020-06-25"),
    endDate: new Date("2025-06-25"),
  },
];
